
[build.environment]
  NPM_FLAGS="--prefix=/"
  NODE_VERSION = "14"

[build]
  command = "npx pnpm i --store=node_modules/.pnpm-store --frozen-lockfile=false && npx pnpm run build && npx pnpm run build:docs"
  publish = "apps/docs/.next"

[[plugins]]
  package = "@netlify/plugin-nextjs"