import { styled } from '@/theme/config'
import { tv } from 'tailwind-variants'
import { Root } from '@radix-ui/react-menubar'

export const menubar = tv({
  slots: {
    base: 'flex bg-mayumi-gray-200',
    trigger: [
      'py-2',
      'px-3',
      'outline-none',
      'select-none',
      'font-medium',
      'leading-none',
      'rounded',
      'text-mayumi-gray-1100',
      'text-[13px]',
      'flex',
      'items-center',
      'justify-between',
      'gap-[2px]',
      'data-[highlighted]:bg-mayumi-gray-500',
      'data-[state=open]:bg-mayumi-gray-500',
    ],
    subtrigger: [
      'group',
      'text-[13px]',
      'leading-none',
      'text-mayumi-gray-1100',
      'rounded',
      'flex',
      'items-center',
      'h-[25px]',
      'px-[10px]',
      'relative',
      'select-none',
      'outline-none',
      'data-[state=open]:bg-mayumi-gray-400',
      'data-[state=open]:text-mayumi-gray-1100',
      'data-[highlighted]:bg-mayumi-gray-500',
      'data-[highlighted]:text-mayumi-gray-1200',
      'data-[highlighted]:data-[state=open]:text-mayumi-gray-1200',
      'data-[disabled]:text-mayumi-gray-800',
      'data-[disabled]:pointer-events-none',
    ],
    content: [
      'min-w-[220px]',
      'bg-mayumi-gray-300',
      'rounded-md',
      'p-[5px]',
      'shadow',
      '[animation-duration:_400ms]',
      '[animation-timing-function:_cubic-bezier(0.16,_1,_0.3,_1)]',
      'will-change-[transform,opacity]',
    ],
    subcontent: [
      'min-w-[220px]',
      'bg-mayumi-gray-300',
      'rounded-md',
      'p-[5px]',
      'shadow',
      '[animation-duration:_400ms]',
      '[animation-timing-function:_cubic-bezier(0.16,_1,_0.3,_1)]',
      'will-change-[transform,opacity]',
    ],
    item: [
      'group',
      'text-[13px]',
      'leading-none',
      'rounded',
      'flex',
      'items-center',
      'h-[25px]',
      'px-[10px]',
      'relative',
      'select-none',
      'outline-none',
      'text-mayumi-gray-1100',
      'data-[state=open]:bg-mayumi-gray-400',
      'data-[state=open]:text-mayumi-gray-1100',
      'data-[highlighted]:bg-mayumi-gray-500',
      'data-[highlighted]:text-mayumi-gray-1200',
      'data-[highlighted]:data-[state=open]:text-mayumi-gray-1200',
      'data-[disabled]:text-mayumi-gray-800',
      'data-[disabled]:pointer-events-none',
    ],
    itemRightSlot: ['ml-auto', 'pl-5'],
  },
  variants: {
    glass: {
      true: {
        content: 'mayumi-glass-3 bg-mayumi-gray-600/60',
        subcontent: 'mayumi-glass-3 bg-mayumi-gray-600/60',
      },
    },
    bordered: {
      true: {
        content: 'border border-mayumi-gray-600 ring-1 ring-black',
        subcontent: 'border border-mayumi-gray-600 ring-1 ring-black',
      },
      false: {
        content: 'border-transparent ring-transparent',
        subcontent: 'border-transparent ring-transparent',
      },
    },
    color: {
      'light-primary': {
        item: [
          'data-[state=open]:bg-mayumi-blue-400',
          'data-[state=open]:text-mayumi-blue-1100',
          'data-[highlighted]:bg-mayumi-blue-500',
          'data-[highlighted]:text-mayumi-blue-1100',
          'data-[highlighted]:data-[state=open]:text-mayumi-blue-1100',
          'data-[disabled]:text-mayumi-blue-800',
        ],
        subtrigger: [
          'data-[state=open]:bg-mayumi-blue-400',
          'data-[state=open]:text-mayumi-gray-1100',
          'data-[highlighted]:bg-mayumi-blue-500',
          'data-[highlighted]:text-mayumi-gray-1200',
          'data-[highlighted]:data-[state=open]:text-mayumi-gray-1100',
          'data-[disabled]:text-mayumi-gray-800',
        ],
      },
      primary: {
        item: [
          'data-[state=open]:bg-mayumi-primary',
          'data-[state=open]:text-mayumi-gray-1200',
          'data-[highlighted]:bg-mayumi-primary',
          'data-[highlighted]:text-mayumi-gray-1200',
          'data-[highlighted]:data-[state=open]:text-mayumi-gray-1200',
          'data-[disabled]:text-mayumi-gray-800',
        ],
        subtrigger: [
          'data-[state=open]:bg-mayumi-primary',
          'data-[state=open]:text-mayumi-gray-1200',
          'data-[highlighted]:bg-mayumi-primary',
          'data-[highlighted]:text-mayumi-gray-1200',
          'data-[highlighted]:data-[state=open]:text-mayumi-gray-1200',
          'data-[disabled]:text-mayumi-gray-800',
        ],
      },
      ghost: {
        item: [
          'data-[state=open]:bg-mayumi-gray-300',
          'data-[state=open]:text-mayumi-gray-1100',
          'data-[highlighted]:bg-mayumi-gray-300',
          'data-[highlighted]:text-mayumi-gray-1200',
          'data-[highlighted]:data-[state=open]:text-mayumi-gray-1100',
          'data-[disabled]:text-mayumi-gray-800',
        ],
        subtrigger: [
          'data-[state=open]:bg-mayumi-gray-300',
          'data-[state=open]:text-mayumi-gray-1100',
          'data-[highlighted]:bg-mayumi-gray-300',
          'data-[highlighted]:text-mayumi-gray-1200',
          'data-[highlighted]:data-[state=open]:text-mayumi-gray-1200',
          'data-[disabled]:text-mayumi-gray-800',
        ],
      },
    },
  },
  defaultVariants: {
    glass: false,
    bordered: false,
  },
})

export const StyledMenuBarRoot = styled(Root, {
  color: '$textColor',
})
